name: follower notifier
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: get follower change
        id: followerChange
        uses: Sorosliu1029/follower-change@v1.0.1
        with:
          myToken: ${{ secrets.MY_TOKEN }}
      - name: email me
        uses: dawidd6/action-send-mail@v3
        if: steps.followerChange.outputs.changed == 'true'
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: GitHub Follower Change
          from: Follower Change Notifier
          to: ${{ secrets.MY_EMAIL }}
          html_body: ${{ steps.followerChange.outputs.markdown }}
          convert_markdown: true
